# -*- coding: utf-8 -*-
"""Task02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N2V25HdaS444dldqORHQxn9_3sFIQw25
"""

import pandas as pd

# Load the dataset
df = pd.read_csv('/content/Au_nanoparticle_dataset.csv')

# Create a new DataFrame by filtering the specified columns
filtered_df = df[['N_total', 'N_bulk', 'N_surface', 'R_avg']]

# Display the head of the new dataframe to verify
print(filtered_df.head())

print(filtered_df.head(20))

description_stats = filtered_df[['N_total', 'N_bulk', 'N_surface', 'R_avg']].describe()
print(description_stats)

import matplotlib.pyplot as plt
import seaborn as sns

features = ['N_total', 'N_bulk', 'N_surface', 'R_avg']

fig, axes = plt.subplots(1, 4, figsize=(20, 5))

for i, feature in enumerate(features):
    sns.histplot(filtered_df[feature], kde=True, ax=axes[i])
    axes[i].set_title(f'Histogram of {feature}')
    axes[i].set_xlabel(feature)
    axes[i].set_ylabel('Frequency')

plt.tight_layout()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

sns.pairplot(filtered_df)
plt.suptitle('Pairplot of N_total, N_bulk, N_surface, and R_avg', y=1.02) # Adjust suptitle position
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# 'filtered_df' is the dataframe containing only the 4 features
g = sns.PairGrid(filtered_df)

# Plots on the upper half: bivariate histogram
g.map_upper(sns.histplot)

# Plots on the diagonal: histogram of each feature along with the kernel density estimation plot
g.map_diag(sns.histplot, kde=True)

# Plots on the lower half: bivariate kernel density estimation plot
g.map_lower(sns.kdeplot)

plt.suptitle('Pairplot: Hist/KDE Diag, Bivariate Hist Upper, Bivariate KDE Lower', y=1.02)
plt.show()