# -*- coding: utf-8 -*-
"""Task01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1suCHPbGy-qTvcPiR_sXVVS4z60Rbr81x
"""

import numpy as np

# Create a random 4x4 array from an exponential distribution
exponential_array = np.random.exponential(scale=1.0, size=(4, 4))
print(exponential_array)

import matplotlib.pyplot as plt
import numpy as np

# Create data for different distributions
n_samples = 100000

# Uniform distribution (as provided by user)
uniform_data = np.random.rand(n_samples)

# Exponential distribution (using scale=1.0, same as in the previous step)
exponential_data = np.random.exponential(scale=1.0, size=n_samples)

# Normal distribution (mean=0, standard deviation=1)
normal_data = np.random.normal(loc=0, scale=1, size=n_samples)

# Plotting histograms
plt.figure(figsize=(10, 6)) # Make the plot a bit larger for better visibility

plt.hist(uniform_data, density=True, bins=100, histtype="step", color="blue", label="Uniform (rand)")
plt.hist(exponential_data, density=True, bins=100, histtype="step", color="red", label="Exponential")
plt.hist(normal_data, density=True, bins=100, histtype="step", color="green", label="Normal")

# Adjust the plot view for better visualization
# x-axis: covering ranges for all three distributions
# y-axis: appropriate for density plots
plt.axis([-3, 8, 0, 1.2]) # Adjusted x-axis to cover exponential better, y-axis to provide some margin
plt.legend(loc="upper right") # Adjusted legend location for better readability
plt.title("Comparison of Random Distributions")
plt.xlabel("Value")
plt.ylabel("Density")
plt.grid(True, linestyle='--', alpha=0.7) # Add a grid for better readability
plt.show()

import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D

# Define the range for X and Y
x = np.linspace(-5, 5, 100)
y = np.linspace(-5, 5, 100)

# Create a meshgrid for X and Y
X, Y = np.meshgrid(x, y)

# Calculate Z = X**2 + Y**2
Z = X**2 + Y**2

# Create a new figure and an axes for 3D plotting
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

# Plot the surface
ax.plot_surface(X, Y, Z, cmap='viridis')

# Set labels
ax.set_xlabel('X-axis')
ax.set_ylabel('Y-axis')
ax.set_zlabel('Z-axis')
ax.set_title('3D Plot of Z = X^2 + Y^2')

plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the Pokemon dataset, often used in Seaborn tutorials
try:
    df = sns.load_dataset('pokemon')
except ValueError:
    print("Could not load 'pokemon' dataset directly. Assuming a CSV in sample_data or similar context. Please provide the correct path if not found.")
    # Fallback if direct load fails, though it usually works for standard datasets
    # If the user has a specific file, they would need to specify the path
    # For this example, let's assume it's accessible or skip if not.
    # As an example, if it were in /content/sample_data/pokemon.csv:
    # df = pd.read_csv('/content/sample_data/pokemon.csv')
    df = pd.DataFrame() # Create an empty DataFrame to avoid errors if dataset isn't loaded

if not df.empty:
    # Define the features of interest, correcting 'Sp. Ark' to 'Sp. Atk'
    features = ['hp', 'attack', 'defense', 'sp_atk', 'sp_def', 'speed']
    # Ensure column names match the dataset, which are typically lowercase for seaborn datasets
    # df.columns = df.columns.str.lower() # Uncomment if column names need to be lowercased

    # Filter the DataFrame for the specified features
    # Check if all features exist in the DataFrame
    available_features = [f for f in features if f in df.columns]
    if len(available_features) != len(features):
        missing_features = set(features) - set(available_features)
        print(f"Warning: Some specified features were not found in the dataset: {missing_features}. Using available features: {available_features}")

    df_features = df[available_features]

    # Calculate Pearson correlation coefficient
    pearson_corr = df_features.corr(method='pearson')

    # Calculate Spearman rank correlation coefficient
    spearman_corr = df_features.corr(method='spearman')

    # Visualize Pearson correlation with a heatmap
    plt.figure(figsize=(8, 6))
    sns.heatmap(pearson_corr, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
    plt.title('Pearson Standard Coefficient Correlation Heatmap')
    plt.show()

    # Visualize Spearman rank correlation with a heatmap
    plt.figure(figsize=(8, 6))
    sns.heatmap(spearman_corr, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
    plt.title('Spearman Rank Correlation Heatmap')
    plt.show()
else:
    print("Dataset could not be loaded, skipping correlation and heatmap visualization.")